import Head from "next/head";
import Input from "crud/components/input";

import { api } from "crud/utils/api";
import React, { useEffect, useState } from "react";
import { Trash } from "@phosphor-icons/react/Trash";
import { Pencil } from "@phosphor-icons/react/Pencil";
export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const post = api.postapi.postSample.useMutation();
  const get = api.getapi.getSample.useQuery();
  const [inputs, setInputs] = useState({ name: "", nickname: "", address: "" });

  const getInputData = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    const u = { [name]: value };

    setInputs((prev) => ({ ...prev, ...u }));
  };
  const sendInput = () => {
    if (inputs.name !== "" || inputs.nickname !== "" || inputs.address !== "") {
      post.mutate(inputs);
      setInputs({ name: "", nickname: "", address: "" });
    } else {
      alert("All fields are required!");
    }
  };
  const [data, setData] = useState(get?.data?.users);

  useEffect(() => {
    setData(get?.data?.users);
  }, [get?.data?.users]);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <form>
          <div className="mb-3">
            <Input
              name="name"
              type="text"
              placeholder="Enter Name"
              onChange={getInputData}
            />
          </div>
          <div className="mb-3">
            <Input
              name="nickname"
              type="text"
              placeholder="Enter Nickname"
              onChange={getInputData}
            />
          </div>
          <div className="mb-3">
            <Input
              name="address"
              type="text"
              placeholder="Enter Email Address"
              onChange={getInputData}
            />
          </div>
          <div>
            <button
              type="submit"
              onClick={() => {
                sendInput();
              }}
              className="btn btn-outline btn-success"
            >
              Submit
            </button>
          </div>
        </form>

        <div className="overflow-x-auto">
          <table className="table table-zebra">
            {/* head */}
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Nickname</th>
                <th>Address</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {data?.map((item, index) => {
                return (
                  <tr key={index}>
                    <th>{index + 1}</th>
                    <td>{item.name}</td>
                    <td>{item.nickname}</td>
                    <td>{item.address}</td>
                    <td>
                      <button
                        value={item.id}
                        className="btn btn-error btn-sm m-1"
                      >
                        <Trash size={20} color="#ffffff" />
                      </button>
                      <button
                        value={item.id}
                        className="btn btn-info btn-sm m-1"
                        onClick={(e) => {
                          console.log(e.currentTarget.value);
                        }}
                      >
                        <Pencil size={20} color="#ffffff" />
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
